### ISSUE TITLE
Unable to Programmatically Set Time...

### ISSUE THREAD

**Issue by BallisticPain** [xdan/periodpicker#33]
So we calculate the time it takes to get from one point to the other and try to adjust the PeriodPicker date and time accordingly... we set it using...

```
        function changeDateTimeSelection (legid, legpoint, time) {
            $.ajax({
                method:'post',
                url:Routing.generate('airnav_account_change_date_time_selection',{
                    legID: legid,
                    legPoint: legpoint
                }),
                data: {time: time},
                dataType: 'json',
                success: function (data) {
                    if (data) {
                        if (data.eta) {
                            console.log(data.eta);
                            $('input.js-datetimepicker[data-legid='+data.legid+'][data-legpoint=end]').val(data.eta);
                            $('input.js-datetimepicker[data-legid='+data.legid+'][data-legpoint=end]').periodpicker('value', data.eta);
                            console.log($('input.js-datetimepicker[data-legid='+data.legid+'][data-legpoint=end]').periodpicker('valueString'));
                            console.log($('input.js-datetimepicker[data-legid='+data.legid+'][data-legpoint=end]').periodpicker('valueStringStrong'));
                            $('input.js-datetimepicker[data-legid='+data.legid+'][data-legpoint=end]').periodpicker('change');
                        }

                        if (data.startEncounterButton) {
                            getEncounterButtons(legid, 'start');
                        }
                        if (data.endEncounterButton) {
                            getEncounterButtons(legid, 'end');
                        }
                        getSendToFboButton(legid);
                        getCloseButton(legid);
                    }
                }
            })
        }
```

None of the methods of setting the time are working for us. It leaves the time at the default time.

We are since the update also experiencing another issue related to not being able to set the time at all through the period picker if we select a date. I'll get more details on that as I move forward.

Thanks,
Jarvis

**Comment by BallisticPain** [comment]
So v4.5.0 fixed my time setting issue, however, I'm having an issue that when I select a date it returns my time to 00:00, and then won't let me mouse click to set the time. If I use the arrow keys on the keyboard a few times it starts allowing me to set the time, and then I can also use the mouse... thoughts?

The above code applies... I changed the `if (data.eta) {` section.

```
                        if (data.eta) {
                            $('input.js-datetimepicker[data-legid='+data.legid+'][data-legpoint=end]').periodpicker('value', data.eta);
                            $('input.js-datetimepicker[data-legid='+data.legid+'][data-legpoint=end]').periodpicker('change');
                        }
```

When I used `.val()` it didn't work setting the time. When I used the above it worked great programmatically setting the time.

Thanks,
Jarvis

**Comment by groovenectar** [comment]
I'm running into this too.. When I select a date, the timepicker stops working. I'm also able to reproduce the behavior when using the keyboard to select, the mouse will start working again...

**Comment by groovenectar** [comment]
It looks like once the keyboard is used, everything starts working normally and you can also select a different date then change the time. This does not apply if the keyboard is used before the date is changed / mouse stops working.

@BallisticPain, are you getting that too?

**Comment by groovenectar** [comment]
This should help! When I set useTimepickerLimits to false, the issue is gone and it works normally. This works fine in my case since I'm only selecting one date.

**Comment by BallisticPain** [comment]
I will test your comments on Tuesday. Thanks for your input! I look forward to a fix and hope your work around will solve the issue for us as well.

**Comment by groovenectar** [comment]
Any findings?

**Comment by BallisticPain** [comment]
Just got my repository caught up... Will test shortly...

**Comment by BallisticPain** [comment]
I'm only selecting one date as well, but the useTimepickerLimits does not solve it for me. :(

I still have the issue, though you are correct that once I use the keyboard to "unlock" it it continues to work even with a new date selection.

**Comment by xdan** [comment]
Hi, update please. I think was fixed in 4.6.5

**Comment by a-jackson** [comment]
I thought this might mean #35 was also fixed but I'm still having the problem of it setting the start time to midnight in 4.7.3

**Comment by BallisticPain** [comment]
@xdan Unfortunately as with @a-jackson, I'm using 4.7.3 and this is still happening for us.

You can test this on the demo page... All of the examples with a timepicker have the same issue(s) or similar ones. The time picker that has a period span as well does some fun stuff... like first it resets to 12 if you set a time first, THEN set the end time and reset the start date, and it resets the start time to the end time.

**Comment by xdan** [comment]
Which format is variable data.eta ? Can you write example without your server (without ajax)?

**Comment by a-jackson** [comment]
``` html
<body>
    <div>
        <input type="text" id="periodpickerstart"/>
        <input type="text" id="periodpickerend"/>
    </div>
    <button onclick="changeDate()">Change Date</button>
<script>
jQuery('#periodpickerstart').periodpicker({
    end: jQuery('#periodpickerend'),
    formatDateTime: 'YYYY-MM-DD HH:mm:ss',
    formatDate: 'YYYY-MM-DD',
    cells: [1, 1], // show only one month
    timepicker: true, // use timepicker
    timepickerOptions: {
        hours: true,
        minutes: true,
        seconds: false,
        ampm: false,
        twelveHoursFormat: false
    }
});
function changeDate() {
    jQuery('#periodpickerstart').periodpicker('value', ['2016-06-01 10:00:00', '2016-06-01 12:00:00']);
}
</script>
</body>
```

Only seems to be an issue when the dates are the same but the times are different.

**Comment by xdan** [comment]
Fixed in 4.7.9

**Comment by a-jackson** [comment]
Can you make this available to download. When I request the download I get 4.7.8.

**Comment by BallisticPain** [comment]
I will test again soon.

Thanks for another update @xdan!

**Comment by groovenectar** [comment]
How can I get the upgrade after it's purchased? The link on my email receipt says that the link has expired, can't seem to find where to get the upgrade.

**Comment by xdan** [comment]
@groovenectar  http://xdsoft.net/jqplugins/periodpicker/?update#plugin_sender 
the new version will come to you by mail

**Comment by BallisticPain** [comment]
@xdan ... I downloaded and got version 4.7.8 like @a-jackson ... It's not fixed in 4.7.8 (which I didn't expect, but figured I would test anyways).

Which btw, here is my setup for most of my date/period picker controls...

```
        options = {
            formatDate: 'MM/DD/YYYY HH:mm',
            formatDateTime: 'MM/DD/YYYY HH:mm',
            formatDecoreDate: 'MM/DD/YYYY HH:mm',
            formatDecoreDateTime: 'MM/DD/YYYY HH:mm',
            formatDecoreDateWithYear: 'MM/DD/YYYY HH:mm',
            formatDecoreDateTimeWithYear: 'MM/DD/YYYY HH:mm',
            norange: true,
            cells: [1, 2],
            resizeButton: false,
            fullsizeButton: false,
            fullsizeOnDblClick: false,
            timepicker: true,
            timepickerOptions: {
                twelveHoursFormat: false,
                hours: true,
                minutes: true,
                seconds: false,
                ampm: true
            },
            yearsLine: false,
            lang: 'en',
            clearButtonInButton: true,
            draggable: false
        };
```

Those are the options anyways... I just pass that into `$(selector).periodpicker(options);`

@a-jackson Thanks for providing an example for @xdan to work from!

Thanks!
Jarvis

**Comment by BallisticPain** [comment]
@xdan 
If the demo/documentation site is updated to 4.7.9 then it's still broken...
Search the page for `useTimepickerLimits` ... there is an example control literally right on top of this text that exemplifies the issue. (To my knowledge EVERY example control with a date + time selection has this issue on the page).
Instead of searching the page you can go to this link: http://xdsoft.net/jqplugins/periodpicker/#timepicker (It's the very next control after that text, and for me it's the only one visible when I go to the page using that link). You optionally can go to: http://xdsoft.net/jqplugins/periodpicker/#useTimepickerLimits and scroll up to see the control I'm specifically referencing as a good example that shows it's not just my code somehow causing the issue.

Change the time from 12:00 to anything other than 12:00. Next select a date. The moment you click a date it moves the time back to 12:00. Also if you try to re-select a time after you select a date it won't move from 12:00. If you don't select something other than 12, and click a date, you still won't be able to change the time after.

I'm able to now programmatically set the time (and have been since v4.5.0), but I can not select a time then the date without the time resetting since that time and before it.

Thanks for your efforts!

**Comment by xdan** [comment]
@BallisticPain  Try now 4.8.0

**Comment by xdan** [comment]
@BallisticPain  Try now 4.8.0

**Comment by BallisticPain** [comment]
@xdan My issue is fixed in 4.8.2 

@a-jackson I hope this fixes the issue you're discussing as well. I'm going to close my issue since you have your own issue. Please feel free to post here if you think I should re-open the ticket.

@groovenectar I hope this works for you as well.

Thanks for everyone's efforts in reporting and fixing!
Jarvis

**Comment by Willy81** [comment]
Sorry, I know this is an old issue, but I'm struggling to set the time programatically in version 6.1.8. I wrote a simple test program based on code posted above by @a-jackson and I get the following error:
```
jquery.periodpicker.full.min.js:15 Uncaught TypeError: Cannot read property 'timepicker' of undefined
    at HTMLInputElement.<anonymous> (jquery.periodpicker.full.min.js:15)
    at Function.each (jquery.min.js:2)
    at m.fn.init.each (jquery.min.js:2)
    at m.fn.init.a.fn.periodpicker (jquery.periodpicker.full.min.js:15)
    at changeDate (test.html:47)
    at HTMLButtonElement.onclick (test.html:30)
```

My code is
```
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Period Picker Demo</title>
	<link rel="stylesheet" href="build/jquery.periodpicker.min.css">
	<link rel="stylesheet" href="build/jquery.timepicker.min.css">
	<script src="jquery.min.js"></script>
	<script src="build/jquery.periodpicker.full.min.js"></script>
	<link rel="stylesheet" href="build/jquery.timepicker.min.css">
	<script src="build/jquery.timepicker.min.js"></script>
    <style>
        pre {
            font-family: Consolas, 'Liberation Mono', Courier, monospace;
            color: #f0f0f0;
            background: #3f3f3f;
            border-radius: 3px;
            white-space: pre-wrap;
            tab-size: 2em;
            padding:10px;
            font-family: Menlo, Monaco, monospace, sans-serif;
        }
    </style>
</head>
<body>
    <div>
        <input type="text" id="periodpickerstart"/>
        <input type="text" id="periodpickerend"/>
    </div>
    <button onclick="changeDate()">Change Date</button>
<script>
jQuery('#periodpickerstart').periodpicker({
    end: jQuery('#periodpickerend'),
    formatDateTime: 'YYYY-MM-DD HH:mm:ss',
    formatDate: 'YYYY-MM-DD',
    cells: [1, 1], // show only one month
    timepicker: true, // use timepicker
    timepickerOptions: {
        hours: true,
        minutes: true,
        seconds: false,
        ampm: false,
        twelveHoursFormat: false
    }
});
function changeDate() {
    jQuery('#periodpickerstart').periodpicker('value', ['2016-06-01 10:00:00', '2016-06-01 12:00:00']);
}
</script>
</body>
```
